export default {
  total_count: 7709550,
  incomplete_results: false,
  items: [
    {
      name: "hello-algorithm",
      stargazers_count: 25795,
      language: "Java",
      html_url: "https://github.com/geekxh/hello-algorithm",
      created_at: "2020-05-29T05:47:09Z",
    },
    {
      name: "design-resources-for-developers",
      stargazers_count: 25511,
      language: null,
      html_url: "https://github.com/bradtraversy/design-resources-for-developers",
      created_at: "2020-05-06T14:40:35Z",
    },
    {
      name: "vite",
      stargazers_count: 23554,
      language: "TypeScript",
      html_url: "https://github.com/vitejs/vite",
      created_at: "2020-04-21T05:03:57Z",
    },
    {
      name: "github-readme-stats",
      stargazers_count: 21494,
      language: "JavaScript",
      html_url: "https://github.com/anuraghazra/github-readme-stats",
      created_at: "2020-07-09T10:34:22Z",
    },
    {
      name: "Web-Dev-For-Beginners",
      stargazers_count: 20811,
      language: "JavaScript",
      html_url: "https://github.com/microsoft/Web-Dev-For-Beginners",
      created_at: "2020-11-10T02:44:00Z",
    },
    {
      name: "Depix",
      stargazers_count: 17549,
      language: "Python",
      html_url: "https://github.com/beurtschipper/Depix",
      created_at: "2020-12-06T12:39:08Z",
    },
    {
      name: "coder2gwy",
      stargazers_count: 16976,
      language: null,
      html_url: "https://github.com/coder2gwy/coder2gwy",
      created_at: "2020-12-30T14:40:50Z",
    },
    {
      name: "Docker-OSX",
      stargazers_count: 13346,
      language: "Shell",
      html_url: "https://github.com/sickcodes/Docker-OSX",
      created_at: "2020-06-04T11:01:37Z",
    },
    {
      name: "avatarify-python",
      stargazers_count: 13198,
      language: "Python",
      html_url: "https://github.com/alievk/avatarify-python",
      created_at: "2020-04-06T19:53:16Z",
    },
    {
      name: "Recoil",
      stargazers_count: 12360,
      language: "JavaScript",
      html_url: "https://github.com/facebookexperimental/Recoil",
      created_at: "2020-05-04T19:44:15Z",
    },
    {
      name: "ar-cutpaste",
      stargazers_count: 12356,
      language: "TypeScript",
      html_url: "https://github.com/cyrildiagne/ar-cutpaste",
      created_at: "2020-05-02T18:40:00Z",
    },
    {
      name: "PaddleOCR",
      stargazers_count: 11488,
      language: "Python",
      html_url: "https://github.com/PaddlePaddle/PaddleOCR",
      created_at: "2020-05-08T10:38:16Z",
    },
    {
      name: "algorithm-pattern",
      stargazers_count: 11355,
      language: "Go",
      html_url: "https://github.com/greyireland/algorithm-pattern",
      created_at: "2020-06-13T15:29:21Z",
    },
    {
      name: "deskreen",
      stargazers_count: 10231,
      language: "TypeScript",
      html_url: "https://github.com/pavlobu/deskreen",
      created_at: "2020-08-08T13:24:18Z",
    },
    {
      name: "ImHex",
      stargazers_count: 10175,
      language: "C++",
      html_url: "https://github.com/WerWolv/ImHex",
      created_at: "2020-11-10T14:27:00Z",
    },
    {
      name: "gpt-3",
      stargazers_count: 10060,
      language: null,
      html_url: "https://github.com/openai/gpt-3",
      created_at: "2020-05-18T08:03:50Z",
    },
    {
      name: "yolov5",
      stargazers_count: 9954,
      language: "Python",
      html_url: "https://github.com/ultralytics/yolov5",
      created_at: "2020-05-18T03:45:11Z",
    },
    {
      name: "AI-Expert-Roadmap",
      stargazers_count: 9768,
      language: "JavaScript",
      html_url: "https://github.com/AMAI-GmbH/AI-Expert-Roadmap",
      created_at: "2020-10-24T21:49:40Z",
    },
    {
      name: "applied-ml",
      stargazers_count: 9547,
      language: null,
      html_url: "https://github.com/eugeneyan/applied-ml",
      created_at: "2020-07-04T18:57:47Z",
    },
    {
      name: "foam",
      stargazers_count: 9481,
      language: "TypeScript",
      html_url: "https://github.com/foambubble/foam",
      created_at: "2020-06-19T17:04:10Z",
    },
    {
      name: "GHunt",
      stargazers_count: 9276,
      language: "Python",
      html_url: "https://github.com/mxrch/GHunt",
      created_at: "2020-10-02T11:26:03Z",
    },
    {
      name: "element-plus",
      stargazers_count: 9166,
      language: "Vue",
      html_url: "https://github.com/element-plus/element-plus",
      created_at: "2020-07-21T06:51:19Z",
    },
    {
      name: "rocky",
      stargazers_count: 9117,
      language: null,
      html_url: "https://github.com/rocky-linux/rocky",
      created_at: "2020-12-08T20:56:26Z",
    },
    {
      name: "Server",
      stargazers_count: 8784,
      language: "HTML",
      html_url: "https://github.com/PanDownloadServer/Server",
      created_at: "2020-06-26T15:41:53Z",
    },
    {
      name: "Bringing-Old-Photos-Back-to-Life",
      stargazers_count: 8099,
      language: "Python",
      html_url: "https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life",
      created_at: "2020-06-24T06:37:58Z",
    },
    {
      name: "maui",
      stargazers_count: 7960,
      language: "C#",
      html_url: "https://github.com/dotnet/maui",
      created_at: "2020-05-08T18:11:05Z",
    },
    {
      name: "Luckysheet",
      stargazers_count: 7657,
      language: "JavaScript",
      html_url: "https://github.com/mengshukeji/Luckysheet",
      created_at: "2020-05-15T07:24:59Z",
    },
    {
      name: "social-analyzer",
      stargazers_count: 7567,
      language: "JavaScript",
      html_url: "https://github.com/qeeqbox/social-analyzer",
      created_at: "2020-11-30T19:04:26Z",
    },
    {
      name: "Awesome-Profile-README-templates",
      stargazers_count: 7563,
      language: "JavaScript",
      html_url: "https://github.com/kautukkundan/Awesome-Profile-README-templates",
      created_at: "2020-07-09T07:38:21Z",
    },
    {
      name: "upptime",
      stargazers_count: 7219,
      language: null,
      html_url: "https://github.com/upptime/upptime",
      created_at: "2020-08-08T16:34:41Z",
    },
    {
      name: "practical-python",
      stargazers_count: 7207,
      language: "Python",
      html_url: "https://github.com/dabeaz-course/practical-python",
      created_at: "2020-05-24T19:50:08Z",
    },
    {
      name: "30-Days-Of-React",
      stargazers_count: 7193,
      language: "JavaScript",
      html_url: "https://github.com/Asabeneh/30-Days-Of-React",
      created_at: "2020-09-29T13:38:54Z",
    },
    {
      name: "go-zero",
      stargazers_count: 7172,
      language: "Go",
      html_url: "https://github.com/tal-tech/go-zero",
      created_at: "2020-08-07T15:37:57Z",
    },
    {
      name: "YesPlayMusic",
      stargazers_count: 7162,
      language: "JavaScript",
      html_url: "https://github.com/qier222/YesPlayMusic",
      created_at: "2020-10-09T10:04:21Z",
    },
    {
      name: "data-engineer-roadmap",
      stargazers_count: 7131,
      language: null,
      html_url: "https://github.com/datastacktv/data-engineer-roadmap",
      created_at: "2020-09-02T13:38:54Z",
    },
    {
      name: "macintosh.js",
      stargazers_count: 7094,
      language: "JavaScript",
      html_url: "https://github.com/felixrieseberg/macintosh.js",
      created_at: "2020-07-14T19:45:49Z",
    },
    {
      name: "vscode-drawio",
      stargazers_count: 7088,
      language: "TypeScript",
      html_url: "https://github.com/hediet/vscode-drawio",
      created_at: "2020-05-08T16:14:10Z",
    },
    {
      name: "LeetcodeTop",
      stargazers_count: 6991,
      language: null,
      html_url: "https://github.com/afatcoder/LeetcodeTop",
      created_at: "2020-07-01T04:47:22Z",
    },
    {
      name: "tsunami-security-scanner",
      stargazers_count: 6877,
      language: "Java",
      html_url: "https://github.com/google/tsunami-security-scanner",
      created_at: "2020-06-03T16:20:00Z",
    },
    {
      name: "Clone-Wars",
      stargazers_count: 6795,
      language: null,
      html_url: "https://github.com/GorvGoyl/Clone-Wars",
      created_at: "2020-12-02T11:10:16Z",
    },
    {
      name: "umami",
      stargazers_count: 6589,
      language: "JavaScript",
      html_url: "https://github.com/mikecao/umami",
      created_at: "2020-07-17T07:59:00Z",
    },
    {
      name: "remotion",
      stargazers_count: 6588,
      language: "TypeScript",
      html_url: "https://github.com/JonnyBurger/remotion",
      created_at: "2020-06-23T19:49:10Z",
    },
    {
      name: "detr",
      stargazers_count: 6574,
      language: "Python",
      html_url: "https://github.com/facebookresearch/detr",
      created_at: "2020-05-26T23:54:52Z",
    },
    {
      name: "dogehouse",
      stargazers_count: 6566,
      language: "TypeScript",
      html_url: "https://github.com/benawad/dogehouse",
      created_at: "2021-02-12T14:54:47Z",
    },
    {
      name: "GamestonkTerminal",
      stargazers_count: 6515,
      language: "Python",
      html_url: "https://github.com/DidierRLopes/GamestonkTerminal",
      created_at: "2020-12-20T10:46:38Z",
    },
    {
      name: "Learn-Vim",
      stargazers_count: 6071,
      language: null,
      html_url: "https://github.com/iggredible/Learn-Vim",
      created_at: "2020-07-13T13:27:44Z",
    },
    {
      name: "bpytop",
      stargazers_count: 6066,
      language: "Python",
      html_url: "https://github.com/aristocratos/bpytop",
      created_at: "2020-07-01T17:41:25Z",
    },
    {
      name: "awesome-github-profile-readme",
      stargazers_count: 6040,
      language: "Vue",
      html_url: "https://github.com/abhisheknaiidu/awesome-github-profile-readme",
      created_at: "2020-07-12T12:57:25Z",
    },
    {
      name: "hackingtool",
      stargazers_count: 5960,
      language: "Python",
      html_url: "https://github.com/Z4nzu/hackingtool",
      created_at: "2020-04-11T09:21:31Z",
    },
    {
      name: "minGPT",
      stargazers_count: 5952,
      language: "Jupyter Notebook",
      html_url: "https://github.com/karpathy/minGPT",
      created_at: "2020-08-17T07:08:48Z",
    },
    {
      name: "duf",
      stargazers_count: 5871,
      language: "Go",
      html_url: "https://github.com/muesli/duf",
      created_at: "2020-09-20T21:22:38Z",
    },
    {
      name: "easy_rust",
      stargazers_count: 5844,
      language: "Shell",
      html_url: "https://github.com/Dhghomon/easy_rust",
      created_at: "2020-07-11T05:54:06Z",
    },
    {
      name: "98.css",
      stargazers_count: 5755,
      language: "CSS",
      html_url: "https://github.com/jdan/98.css",
      created_at: "2020-04-17T01:39:53Z",
    },
    {
      name: "free",
      stargazers_count: 5716,
      language: null,
      html_url: "https://github.com/freefq/free",
      created_at: "2020-06-07T02:48:33Z",
    },
    {
      name: "headlessui",
      stargazers_count: 5649,
      language: "TypeScript",
      html_url: "https://github.com/tailwindlabs/headlessui",
      created_at: "2020-09-16T09:53:09Z",
    },
    {
      name: "pulse",
      stargazers_count: 5521,
      language: "Python",
      html_url: "https://github.com/adamian98/pulse",
      created_at: "2020-05-20T17:58:16Z",
    },
    {
      name: "how-to-secure-anything",
      stargazers_count: 5514,
      language: null,
      html_url: "https://github.com/veeral-patel/how-to-secure-anything",
      created_at: "2020-04-06T04:53:55Z",
    },
    {
      name: "bit",
      stargazers_count: 5456,
      language: "Go",
      html_url: "https://github.com/chriswalz/bit",
      created_at: "2020-09-11T00:50:18Z",
    },
    {
      name: "rough-notation",
      stargazers_count: 5430,
      language: "TypeScript",
      html_url: "https://github.com/rough-stuff/rough-notation",
      created_at: "2020-05-25T06:34:03Z",
    },
    {
      name: "InfoSpider",
      stargazers_count: 5397,
      language: "Python",
      html_url: "https://github.com/kangvcar/InfoSpider",
      created_at: "2020-07-11T14:47:37Z",
    },
    {
      name: "screenity",
      stargazers_count: 5324,
      language: "JavaScript",
      html_url: "https://github.com/alyssaxuu/screenity",
      created_at: "2020-11-01T15:16:31Z",
    },
    {
      name: "tailblocks",
      stargazers_count: 5300,
      language: "JavaScript",
      html_url: "https://github.com/mertJF/tailblocks",
      created_at: "2020-05-14T18:26:36Z",
    },
    {
      name: "eul",
      stargazers_count: 5252,
      language: "Swift",
      html_url: "https://github.com/gao-sun/eul",
      created_at: "2020-06-26T07:10:17Z",
    },
    {
      name: "pdf",
      stargazers_count: 5124,
      language: null,
      html_url: "https://github.com/itdevbooks/pdf",
      created_at: "2021-01-22T11:30:15Z",
    },
    {
      name: "IT_book",
      stargazers_count: 5077,
      language: null,
      html_url: "https://github.com/XiangLinPro/IT_book",
      created_at: "2020-04-27T08:16:17Z",
    },
    {
      name: "3d-photo-inpainting",
      stargazers_count: 5048,
      language: "Python",
      html_url: "https://github.com/vt-vl-lab/3d-photo-inpainting",
      created_at: "2020-04-08T15:31:45Z",
    },
    {
      name: "L-ink_Card",
      stargazers_count: 4985,
      language: "C",
      html_url: "https://github.com/peng-zhihui/L-ink_Card",
      created_at: "2020-06-20T10:49:48Z",
    },
    {
      name: "DearPyGui",
      stargazers_count: 4825,
      language: "C++",
      html_url: "https://github.com/hoffstadt/DearPyGui",
      created_at: "2020-05-28T17:12:57Z",
    },
    {
      name: "qlib",
      stargazers_count: 4732,
      language: "Python",
      html_url: "https://github.com/microsoft/qlib",
      created_at: "2020-08-14T06:46:00Z",
    },
    {
      name: "GitHub520",
      stargazers_count: 4660,
      language: "Python",
      html_url: "https://github.com/521xueweihan/GitHub520",
      created_at: "2020-05-13T07:25:21Z",
    },
    {
      name: "best-of-ml-python",
      stargazers_count: 4581,
      language: "Python",
      html_url: "https://github.com/ml-tooling/best-of-ml-python",
      created_at: "2020-11-29T19:41:36Z",
    },
    {
      name: "howtheysre",
      stargazers_count: 4576,
      language: "JavaScript",
      html_url: "https://github.com/upgundecha/howtheysre",
      created_at: "2021-02-14T14:03:02Z",
    },
    {
      name: "Yet-Another-EfficientDet-Pytorch",
      stargazers_count: 4572,
      language: "Jupyter Notebook",
      html_url: "https://github.com/zylo117/Yet-Another-EfficientDet-Pytorch",
      created_at: "2020-04-06T03:27:06Z",
    },
    {
      name: "css-in-readme-like-wat",
      stargazers_count: 4535,
      language: null,
      html_url: "https://github.com/sindresorhus/css-in-readme-like-wat",
      created_at: "2020-07-21T16:02:52Z",
    },
    {
      name: "Learn-Data-Science-For-Free",
      stargazers_count: 4524,
      language: null,
      html_url: "https://github.com/therealsreehari/Learn-Data-Science-For-Free",
      created_at: "2021-01-27T13:02:06Z",
    },
    {
      name: "cosmopolitan",
      stargazers_count: 4523,
      language: "C",
      html_url: "https://github.com/jart/cosmopolitan",
      created_at: "2020-06-15T14:16:13Z",
    },
    {
      name: "machine-learning-roadmap",
      stargazers_count: 4498,
      language: null,
      html_url: "https://github.com/mrdbourke/machine-learning-roadmap",
      created_at: "2020-07-09T07:07:47Z",
    },
    {
      name: "school-of-sre",
      stargazers_count: 4472,
      language: "HTML",
      html_url: "https://github.com/linkedin/school-of-sre",
      created_at: "2020-10-26T23:55:03Z",
    },
    {
      name: "MalwareSourceCode",
      stargazers_count: 4417,
      language: "Assembly",
      html_url: "https://github.com/vxunderground/MalwareSourceCode",
      created_at: "2020-10-10T02:48:57Z",
    },
    {
      name: "vscode-rainbow-fart",
      stargazers_count: 4390,
      language: "JavaScript",
      html_url: "https://github.com/SaekiRaku/vscode-rainbow-fart",
      created_at: "2020-05-29T13:24:08Z",
    },
    {
      name: "ml-visuals",
      stargazers_count: 4379,
      language: null,
      html_url: "https://github.com/dair-ai/ml-visuals",
      created_at: "2020-05-17T13:42:29Z",
    },
    {
      name: "owncast",
      stargazers_count: 4360,
      language: "Go",
      html_url: "https://github.com/owncast/owncast",
      created_at: "2020-05-24T00:58:13Z",
    },
    {
      name: "playwright-python",
      stargazers_count: 4336,
      language: "Python",
      html_url: "https://github.com/microsoft/playwright-python",
      created_at: "2020-07-01T15:28:13Z",
    },
    {
      name: "winapps",
      stargazers_count: 4314,
      language: "Shell",
      html_url: "https://github.com/Fmstrat/winapps",
      created_at: "2020-11-07T21:19:24Z",
    },
    {
      name: "jukebox",
      stargazers_count: 4218,
      language: "Python",
      html_url: "https://github.com/openai/jukebox",
      created_at: "2020-04-29T17:16:12Z",
    },
    {
      name: "tinygrad",
      stargazers_count: 4207,
      language: "Python",
      html_url: "https://github.com/geohot/tinygrad",
      created_at: "2020-10-18T16:23:12Z",
    },
    {
      name: "U-2-Net",
      stargazers_count: 4166,
      language: "Python",
      html_url: "https://github.com/xuebinqin/U-2-Net",
      created_at: "2020-05-04T17:10:28Z",
    },
    {
      name: "Sandboxie",
      stargazers_count: 4157,
      language: "C",
      html_url: "https://github.com/sandboxie-plus/Sandboxie",
      created_at: "2020-04-09T09:26:37Z",
    },
    {
      name: "Pokedex",
      stargazers_count: 4155,
      language: "Kotlin",
      html_url: "https://github.com/skydoves/Pokedex",
      created_at: "2020-06-01T11:19:43Z",
    },
    {
      name: "Xray-core",
      stargazers_count: 4087,
      language: "Go",
      html_url: "https://github.com/XTLS/Xray-core",
      created_at: "2020-11-09T11:23:10Z",
    },
    {
      name: "CodeGuide",
      stargazers_count: 4084,
      language: null,
      html_url: "https://github.com/fuzhengwei/CodeGuide",
      created_at: "2020-04-14T08:54:33Z",
    },
    {
      name: "gpt-neo",
      stargazers_count: 4028,
      language: "Python",
      html_url: "https://github.com/EleutherAI/gpt-neo",
      created_at: "2020-07-05T10:23:46Z",
    },
    {
      name: "super-expressive",
      stargazers_count: 4026,
      language: "JavaScript",
      html_url: "https://github.com/francisrstokes/super-expressive",
      created_at: "2020-07-14T22:04:33Z",
    },
    {
      name: "500-AI-Machine-learning-Deep-learning-Computer-vision-NLP-Projects-with-code",
      stargazers_count: 4025,
      language: null,
      html_url:
        "https://github.com/ashishpatel26/500-AI-Machine-learning-Deep-learning-Computer-vision-NLP-Projects-with-code",
      created_at: "2021-01-02T12:08:37Z",
    },
    {
      name: "github-profile-readme-generator",
      stargazers_count: 4024,
      language: "JavaScript",
      html_url: "https://github.com/rahuldkjain/github-profile-readme-generator",
      created_at: "2020-07-15T11:20:48Z",
    },
    {
      name: "compose-jb",
      stargazers_count: 3892,
      language: "Kotlin",
      html_url: "https://github.com/JetBrains/compose-jb",
      created_at: "2020-09-07T10:40:49Z",
    },
    {
      name: "papercups",
      stargazers_count: 3890,
      language: "Elixir",
      html_url: "https://github.com/papercups-io/papercups",
      created_at: "2020-07-15T14:46:06Z",
    },
    {
      name: "present",
      stargazers_count: 3886,
      language: "Python",
      html_url: "https://github.com/vinayak-mehta/present",
      created_at: "2020-08-18T20:39:05Z",
    },
    {
      name: "type-challenges",
      stargazers_count: 3881,
      language: "TypeScript",
      html_url: "https://github.com/type-challenges/type-challenges",
      created_at: "2020-07-23T14:33:11Z",
    },
    {
      name: "awesome-lowcode",
      stargazers_count: 3857,
      language: null,
      html_url: "https://github.com/taowen/awesome-lowcode",
      created_at: "2020-07-22T14:42:10Z",
    },
  ],
}
